#!/usr/bin/env python3
"""Generate C parameter headers from variant YAML.

Outputs (into --out, default build/generated):
  params_types.h        typedef of params_t, derived from variants/common.yaml
  params_<variant>.h    const params_t instance for one variant
  params_<variant>.json resolved runtime parameter blob (controls + hardware)

Type rules: keys ending in _ms or _mv are int32_t, booleans are bool,
everything else is float.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from variant_loader import list_variants, load_variant  # noqa: E402

HEADER = "/* GENERATED by codegen/gen_params.py from variants/ YAML. Do not edit. */\n"


def c_type(key: str, value) -> str:
    if isinstance(value, bool):
        return "bool"
    if key.endswith("_ms") or key.endswith("_mv"):
        return "int32_t"
    return "float"


def c_value(key: str, value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if c_type(key, value) == "int32_t":
        return str(int(value))
    return f"{float(value)!r}f"


def struct_defs(node: dict, name: str, out: list[str]) -> None:
    fields = []
    for key, value in node.items():
        if isinstance(value, dict):
            sub = f"params_{key}_t" if name == "params_t" else f"{name[:-2]}_{key}_t"
            struct_defs(value, sub, out)
            fields.append(f"    {sub} {key};")
        else:
            fields.append(f"    {c_type(key, value)} {key};")
    out.append("typedef struct {\n" + "\n".join(fields) + f"\n}} {name};\n")


def initializer(node: dict, indent: int) -> str:
    pad = " " * indent
    parts = []
    for key, value in node.items():
        if isinstance(value, dict):
            parts.append(f"{pad}.{key} = {{\n{initializer(value, indent + 4)}\n{pad}}}")
        else:
            parts.append(f"{pad}.{key} = {c_value(key, value)}")
    return ",\n".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="build/generated")
    ap.add_argument("--variant", action="append", help="limit to these variants")
    args = ap.parse_args()
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    variants = args.variant or list_variants()
    reference = load_variant(variants[0])["controls"]
    defs: list[str] = []
    struct_defs(reference, "params_t", defs)
    (out / "params_types.h").write_text(
        HEADER
        + "#ifndef PARAMS_TYPES_H\n#define PARAMS_TYPES_H\n\n#include <stdbool.h>\n#include <stdint.h>\n\n"
        + "\n".join(defs)
        + "\n#endif /* PARAMS_TYPES_H */\n"
    )
    for v in variants:
        cfg = load_variant(v)
        guard = f"PARAMS_{v.upper()}_H"
        (out / f"params_{v}.h").write_text(
            HEADER
            + f"#ifndef {guard}\n#define {guard}\n\n#include \"params_types.h\"\n\n"
            + f"#define ASL200_VARIANT_NAME \"{v}\"\n\n"
            + f"static const params_t PARAMS_ACTIVE = {{\n{initializer(cfg['controls'], 4)}\n}};\n\n"
            + f"#endif /* {guard} */\n"
        )
        (out / f"params_{v}.json").write_text(json.dumps(cfg, indent=2))
    print(f"generated params for {len(variants)} variant(s) in {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
